apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    meta.helm.sh/release-name: docker-mailserver
    meta.helm.sh/release-namespace: mail
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: docker-mailserver
    chart: docker-mailserver-3.0.10
    heritage: Helm
    release: docker-mailserver
  name: docker-mailserver
  namespace: mail
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: docker-mailserver
      release: docker-mailserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: docker-mailserver
        release: docker-mailserver
    spec:
      containers:
      - env:
        - name: ACCOUNT_PROVISIONER
        - name: AMAVIS_LOGLEVEL
          value: "0"
        - name: CLAMAV_MESSAGE_SIZE_LIMIT
        - name: DEFAULT_RELAY_HOST
        - name: DMS_VMAIL_GID
        - name: DMS_VMAIL_UID
        - name: DOVECOT_AUTH_BIND
        - name: DOVECOT_INET_PROTOCOLS
          value: all
        - name: DOVECOT_MAILBOX_FORMAT
          value: maildir
        - name: DOVECOT_PASS_FILTER
        - name: DOVECOT_TLS
        - name: DOVECOT_USER_FILTER
        - name: ENABLE_AMAVIS
          value: "0"
        - name: ENABLE_CLAMAV
          value: "0"
        - name: ENABLE_DNSBL
          value: "0"
        - name: ENABLE_FAIL2BAN
          value: "0"
        - name: ENABLE_FETCHMAIL
          value: "0"
        - name: ENABLE_GETMAIL
          value: "0"
        - name: ENABLE_IMAP
          value: "1"
        - name: ENABLE_MANAGESIEVE
        - name: ENABLE_OPENDKIM
          value: "0"
        - name: ENABLE_OPENDMARC
          value: "0"
        - name: ENABLE_POLICYD_SPF
          value: "0"
        - name: ENABLE_POP3
        - name: ENABLE_POSTGREY
          value: "0"
        - name: ENABLE_QUOTAS
          value: "1"
        - name: ENABLE_RSPAMD
          value: "1"
        - name: ENABLE_RSPAMD_REDIS
          value: "1"
        - name: ENABLE_SASLAUTHD
          value: "0"
        - name: ENABLE_SPAMASSASSIN
          value: "0"
        - name: ENABLE_SPAMASSASSIN_KAM
          value: "0"
        - name: ENABLE_SRS
          value: "0"
        - name: ENABLE_UPDATE_CHECK
          value: "1"
        - name: FAIL2BAN_BLOCKTYPE
          value: drop
        - name: FETCHMAIL_PARALLEL
          value: "0"
        - name: FETCHMAIL_POLL
          value: "300"
        - name: GETMAIL_POLL
          value: "5"
        - name: LDAP_BIND_DN
        - name: LDAP_BIND_PW
        - name: LDAP_QUERY_FILTER_ALIAS
        - name: LDAP_QUERY_FILTER_DOMAIN
        - name: LDAP_QUERY_FILTER_GROUP
        - name: LDAP_QUERY_FILTER_USER
        - name: LDAP_SEARCH_BASE
        - name: LDAP_SERVER_HOST
        - name: LDAP_START_TLS
        - name: LOGROTATE_INTERVAL
          value: weekly
        - name: LOGWATCH_INTERVAL
        - name: LOGWATCH_RECIPIENT
        - name: LOGWATCH_SENDER
        - name: LOG_LEVEL
          value: info
        - name: MARK_SPAM_AS_READ
          value: "0"
        - name: MOVE_SPAM_TO_JUNK
          value: "1"
        - name: NETWORK_INTERFACE
        - name: ONE_DIR
          value: "1"
        - name: OVERRIDE_HOSTNAME
          value: mail.example.com
        - name: PERMIT_DOCKER
          value: none
        - name: PFLOGSUMM_RECIPIENT
        - name: PFLOGSUMM_SENDER
        - name: PFLOGSUMM_TRIGGER
        - name: POSTFIX_DAGENT
        - name: POSTFIX_INET_PROTOCOLS
          value: all
        - name: POSTFIX_MAILBOX_SIZE_LIMIT
        - name: POSTFIX_MESSAGE_SIZE_LIMIT
        - name: POSTFIX_REJECT_UNKNOWN_CLIENT_HOSTNAME
          value: "0"
        - name: POSTGREY_AUTO_WHITELIST_CLIENTS
          value: "5"
        - name: POSTGREY_DELAY
          value: "300"
        - name: POSTGREY_MAX_AGE
          value: "35"
        - name: POSTGREY_TEXT
          value: Delayed by Postgrey
        - name: POSTMASTER_ADDRESS
        - name: POSTSCREEN_ACTION
          value: enforce
        - name: RELAY_HOST
        - name: RELAY_PASSWORD
        - name: RELAY_PORT
          value: "25"
        - name: RELAY_USER
        - name: REPORT_RECIPIENT
        - name: REPORT_SENDER
        - name: RSPAMD_CHECK_AUTHENTICATED
          value: "0"
        - name: RSPAMD_GREYLISTING
          value: "0"
        - name: RSPAMD_HFILTER
          value: "1"
        - name: RSPAMD_HFILTER_HOSTNAME_UNKNOWN_SCORE
          value: "6"
        - name: RSPAMD_LEARN
          value: "0"
        - name: SASLAUTHD_LDAP_AUTH_METHOD
        - name: SASLAUTHD_LDAP_BIND_DN
        - name: SASLAUTHD_LDAP_FILTER
        - name: SASLAUTHD_LDAP_MECH
        - name: SASLAUTHD_LDAP_PASSWORD
        - name: SASLAUTHD_LDAP_PASSWORD_ATTR
        - name: SASLAUTHD_LDAP_SEARCH_BASE
        - name: SASLAUTHD_LDAP_SERVER
        - name: SASLAUTHD_LDAP_START_TLS
        - name: SASLAUTHD_LDAP_TLS_CACERT_DIR
        - name: SASLAUTHD_LDAP_TLS_CACERT_FILE
        - name: SASLAUTHD_LDAP_TLS_CHECK_PEER
        - name: SASLAUTHD_MECHANISMS
        - name: SASLAUTHD_MECH_OPTIONS
        - name: SA_KILL
          value: "10"
        - name: SA_SPAM_SUBJECT
          value: '***SPAM*** '
        - name: SA_TAG
          value: "2"
        - name: SA_TAG2
          value: "6.31"
        - name: SMTP_ONLY
        - name: SPAMASSASSIN_SPAM_TO_INBOX
          value: "1"
        - name: SPOOF_PROTECTION
        - name: SRS_EXCLUDE_DOMAINS
        - name: SRS_SECRET
        - name: SRS_SENDER_CLASSES
          value: envelope_sender
        - name: SSL_ALT_CERT_PATH
        - name: SSL_ALT_KEY_PATH
        - name: SUPERVISOR_LOGLEVEL
        - name: TLS_LEVEL
        - name: TZ
        - name: UPDATE_CHECK_INTERVAL
          value: 1d
        - name: VIRUSMAILS_DELETE_DELAY
        image: mailserver/docker-mailserver:13.3.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - supervisorctl status | grep -E "amavis|clamav|cron|dovecot|mailserver|opendkim|opendmarc|postfix|rsyslog"
              | grep RUNNING
          failureThreshold: 3
          initialDelaySeconds: 300
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: docker-mailserver
        ports:
        - containerPort: 25
          name: smtp
          protocol: TCP
        - containerPort: 465
          name: submissions
          protocol: TCP
        - containerPort: 587
          name: submission
          protocol: TCP
        - containerPort: 10465
          name: subs-proxy
          protocol: TCP
        - containerPort: 10587
          name: sub-proxy
          protocol: TCP
        - containerPort: 143
          name: imap
          protocol: TCP
        - containerPort: 993
          name: imaps
          protocol: TCP
        - containerPort: 10143
          name: imap-proxy
          protocol: TCP
        - containerPort: 10993
          name: imaps-proxy
          protocol: TCP
        - containerPort: 11334
          name: rspamd
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - supervisorctl status | grep -E "mailserver|postfix" | grep RUNNING
          failureThreshold: 3
          initialDelaySeconds: 300
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            ephemeral-storage: 500Mi
            memory: 2Gi
          requests:
            cpu: "1"
            ephemeral-storage: 100Mi
            memory: 1536Mi
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/docker-mailserver/dovecot.cf
          name: dovecot-cf
          subPath: dovecot.cf
        - mountPath: /etc/dovecot/conf.d/10-plugin.conf
          name: fts-xapian-plugin-conf
          subPath: fts-xapian-plugin.conf
        - mountPath: /tmp/docker-mailserver/user-patches.sh
          name: user-patches-sh
          subPath: user-patches.sh
        - mountPath: /tmp/docker-mailserver
          name: mail-config
        - mountPath: /var/mail
          name: mail-data
        - mountPath: /var/log/mail
          name: mail-log
        - mountPath: /var/mail-state
          name: mail-state
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: docker-mailserver
      serviceAccountName: docker-mailserver
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: dovecot-cf
        name: dovecot-cf
      - configMap:
          defaultMode: 420
          name: fts-xapian-plugin-conf
        name: fts-xapian-plugin-conf
      - configMap:
          defaultMode: 420
          name: user-patches-sh
        name: user-patches-sh
      - name: mail-config
        persistentVolumeClaim:
          claimName: docker-mailserver-mail-config
      - name: mail-data
        persistentVolumeClaim:
          claimName: docker-mailserver-mail-data
      - name: mail-log
        persistentVolumeClaim:
          claimName: docker-mailserver-mail-log
      - name: mail-state
        persistentVolumeClaim:
          claimName: docker-mailserver-mail-state
