apiVersion: v1
kind: Service
metadata:
  name: docker-mailserver-esmtp
  namespace: mail
  labels:
    app: docker-mailserver
spec:
  selector:
    app: docker-mailserver

  ports:
    - port: 465
      targetPort: 465
  type: NodePort
